// <auto-generated />
namespace CrmBL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update211223 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update211223));
        
        string IMigrationMetadata.Id
        {
            get { return "202112232201023_update211223"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
